### ISSUE TITLE
windows版本录制就会发生崩溃的情况

### ISSUE THREAD

**Issue by yshtcn** [bililive-go/bililive-go#546]
### 程序版本

0.7.16

### 所使用的 config 文件的内容
```
rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: C:\GreenProgram\ffmpeg\ffmpeg-6.0-full_build\bin
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/382640915103
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000
```
### 程序 log
```
C:\GreenProgram\bililive\bililive-windows-amd64>C:\GreenProgram\bililive\bililive-windows-amd64\bililive-windows-amd64.exe -c config.yml
time="2023-09-12 15:47:24" level=info msg="BiliLive-go Version: v0.7.16 Link Start"
time="2023-09-12 15:47:26" level=info msg="Server start at 127.0.0.1:8080"
time="2023-09-12 15:47:48" level=info msg="Live Start" host="财眼看市" room="欢迎收看《财眼看市》节目"
time="2023-09-12 15:47:48" level=info msg="Record Start" host="财眼看市" room="欢迎收看《财眼看市》节目"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xf436ad]

goroutine 110 [running]:
os.(*Process).signal(0xc00014cb00?, {0x1e9bcc8?, 0x227c4a0?})
        /opt/hostedtoolcache/go/1.19.12/x64/src/os/exec_windows.go:49 +0x4d
os.(*Process).Signal(...)
        /opt/hostedtoolcache/go/1.19.12/x64/src/os/exec.go:138
os.(*Process).kill(...)
        /opt/hostedtoolcache/go/1.19.12/x64/src/os/exec_posix.go:67
os.(*Process).Kill(...)
        /opt/hostedtoolcache/go/1.19.12/x64/src/os/exec.go:123
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).ParseLiveStream(0xc00008c960, {0x1e9d638?, 0xc00028d860?}, 0x15c65a8?, {0x1ea1130, 0xc000334040}, {0xc000318150, 0x61})
        /home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:153 +0x2d5
github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).tryRecord(0xc000258240, {0x1e9d638, 0xc00028d860})
        /home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:159 +0xb68
github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).run(0xc000258240, {0x1e9d638, 0xc00028d860})
        /home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:241 +0x39
created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).Start
        /home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:265 +0xc5
       
```

### 自由描述

运行环境是Windows11，程序是bililive-windows-amd64。在config.yml中配置ffmpeg_path后，可以进入网页。开始录制后，程序会报错退出，报错记录如上（注：我打开了config.yml中的debug。只会print在命令行，不会写入log，debug打开也不会）
```
C:\GreenProgram\bililive\bililive-windows-amd64>C:\GreenProgram\bililive\bililive-windows-amd64\bililive-windows-amd64.exe -c config.yml
time="2023-09-12 15:47:24" level=info msg="BiliLive-go Version: v0.7.16 Link Start"
time="2023-09-12 15:47:26" level=info msg="Server start at 127.0.0.1:8080"
```
尝试更换了ffmpeg版本包括：
- ffmpeg-6.0-essentials_build（最新的release版本）
- ffmpeg-6.0-full_build（最新的release版本）
- ffmpeg-master-latest-win64-gpl（最新的master编译版本）

均不能排除错误。

**Comment by kira1928** [comment]
看代码是执行 ffmpeg 的命令失败了。
因为程序从来没见过执行 ffmpeg 录制直播还能失败的，所以这段 ffmpeg 失败后的错误处理代码中有一个空指针 bug 一直没人发现。
你可能是第一个受害者。

**Comment by wxlg1117** [comment]
我在我的surface pro3 win10 ent 2016 ltsc上也碰上这个问题了,似乎是某天自动更新重启后原来好使的bililive-go和ffmpeg版本也都闪退了,换最新的也不行.但我虚拟机上跑个最新的win10版本似乎又不闪退,难道ffmpeg还有什么依赖库不对就闪退?

**Comment by kira1928** [comment]
🤖 **AI 自动评估：建议关闭（待人工验证）**

（本评论由 AI 自动生成，供维护者参考）

经代码与评论核查，此 issue 已失去实际意义，建议关闭：

> 0.7.x ffmpeg parser 空指针崩溃已修复：commit 4f23b9b『fix ffmpeg nil pointer crash (#767)』，0.8.0 重构后系统消除

请维护者人工验证后处理；若判定有误请忽略本评论。
