### ISSUE TITLE
Windows环境下程序不定时崩溃

### ISSUE THREAD

**Issue by lihui114514** [bililive-go/bililive-go#556]
### 程序版本

0.7.17

### 程序 log

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa8 pc=0x194289b]

goroutine 292728 [running]:
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop.func1()
        /home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:162 +0x1b
sync.(*Once).doSlow(0xc0006fd440?, 0x1948500?)
        /opt/hostedtoolcache/go/1.19.13/x64/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.19.13/x64/src/sync/once.go:65
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop(0xc0009b05a0?)
        /home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:161 +0x45
github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).Close(0x1a167c0?)
        /home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:282 +0x62
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).RemoveRecorder(0xc0003d53e0, {0xc000fb1f78?, 0x8?}, {0xc00054a3e0, 0x20})
        /home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:148 +0xa2
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).registryListener.func3(0xc0009b0840?)
        /home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:69 +0xb7
github.com/hr3lxphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent.func1()
        /home/runner/work/bililive-go/bililive-go/src/pkg/events/dispatcher.go:96 +0x47
created by github.com/hr3lxphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent
        /home/runner/work/bililive-go/bililive-go/src/pkg/events/dispatcher.go:94 +0x235

### 自由描述

windows LTCS 2019的环境，录制正常，但是会不定时的崩溃

**Comment by kira1928** [comment]
是一个有年头的多线程竞争bug了，不会修。。。

**Comment by nyable** [comment]
最近在多台主机上，以默认配置运行启动并开始录制时，均报该错误，必定复现。
环境为Windows 10 以及Windows 10 LTSC 2019 32位。
因为看报错内容有ffmpeg，因此尝试更换了数个版本（6.0以及5.1.2），依然复现。

**Comment by 18202821297** [comment]
> 是一个有年头的多线程竞争bug了，不会修。。。

不改代码的情况下有什么办法可以避免，比如降低ffmpeg版本，换成单线程的那种？

**Comment by kira1928** [comment]
至少我目前想不到解决办法。。

**Comment by kira1928** [comment]
🤖 **AI 自动评估：建议关闭（待人工验证）**

（本评论由 AI 自动生成，供维护者参考）

经代码与评论核查，此 issue 已失去实际意义，建议关闭：

> ffmpeg.go Stop() race panic 已由 commit 0c88ec6『fix ffmpeg race panic (#766)』修复，0.8.0 重构彻底消除

请维护者人工验证后处理；若判定有误请忽略本评论。
