### ISSUE TITLE
连续2次是大概24小时左右的样子会崩溃

### ISSUE THREAD

**Issue by 18202821297** [bililive-go/bililive-go#722]
### 程序版本

v0.7.25

### 程序 log

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa8 pc=0xdc62e3]

goroutine 19484 [running]:
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop.func1()
        /home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:193 +0x23
sync.(*Once).doSlow(0x7e6a09?, 0x1?)
        /opt/hostedtoolcache/go/1.19.13/x64/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.19.13/x64/src/sync/once.go:65
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop(0xc0006b6600?)
        /home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:192 +0x5b
github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).Close(0xe9a9c0?)
        /home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:284 +0x77
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).RemoveRecorder(0xc0005fd350, {0xc00058f380?, 0xc0003da088?}, {0xc0003082e0, 0x20})
        /home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:148 +0xa2
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).registryListener.func3(0xc0003da000?)
        /home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:69 +0xb7
github.com/hr3lxphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent.func1()
        /home/runner/work/bililive-go/bililive-go/src/pkg/events/dispatcher.go:96 +0x47
created by github.com/hr3lxphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent

**Comment by kira1928** [comment]
🤖 **AI 自动评估：建议关闭（待人工验证）**

（本评论由 AI 自动生成，供维护者参考）

经代码与评论核查，此 issue 已失去实际意义，建议关闭：

> panic 位于旧版 ffmpeg parser Stop()（v0.7.25），PR #766（0c88ec6）与 #767（4f23b9b）直接修复竞态/空指针，现 master Stop() 有 closeOnce/cmdLock/nil 守卫

请维护者人工验证后处理；若判定有误请忽略本评论。
